name: Deploy Blog

on:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      # Output in ./dist/

      # Step 1: SSH to server, clean all except cpanel files and .htaccess
      - name: Clean target folder
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 64000
          script: |
            find /home/pikomoto/blog.pikomo.top/ -mindepth 1 \
              ! -name '.htaccess*' \
              ! -name '.well-known' \
              ! -path '/home/pikomoto/blog.pikomo.top/.well-known/*' \
              ! -name 'cgi-bin' \
              ! -path '/home/pikomoto/blog.pikomo.top/cgi-bin/*' \
              ! -name 'error_log' \
              -delete

      # Step 2: Copy ./dist/ from VM to server
      - name: Upload dist to server
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz
          path: dist/
          remote_path: /home/pikomoto/blog.pikomo.top/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: 64000
